version: '3.8'

networks:
  app_network:
    driver: bridge

services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    env_file:
      - .env  
    depends_on:
      - redis
    networks:
      - app_network  
    container_name: app 
  
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - app_network  
    container_name: redis 

name: Multilingual_FAQ_System_with_Flask
